/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07;

/**
 *
 * @author anriu
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDigiteOValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        cbTipos = new javax.swing.JComboBox<>();
        lblEscolha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblRecibo = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(39, 58, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("PAGAMENTOS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lblDigiteOValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDigiteOValor.setForeground(new java.awt.Color(255, 255, 255));
        lblDigiteOValor.setText("Digite o valor do pagamento:");
        jPanel1.add(lblDigiteOValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtValor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 150, -1));

        cbTipos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Pix" }));
        cbTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTiposActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblEscolha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEscolha.setForeground(new java.awt.Color(255, 255, 255));
        lblEscolha.setText("Escolha a forma de pagamento");
        jPanel1.add(lblEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        lblRecibo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRecibo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 390, 210));

        lblTexto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("RECIBO");
        jPanel1.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void cbTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTiposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Pegando o valor digitado pelo usuario assim como vendo qual o metodo de pagamento
        double valor = Double.parseDouble(txtValor.getText());
        String metodo = (String) cbTipos.getSelectedItem();
        
        //Iniciando uma nova interface do tipo Pagamento
        Pagamento pagamento;
        
        
        //Caso seja por dinheiro
        if("Dinheiro".equals(metodo)){
            //Usando uma variavel do tipo PagamentoDinhiro apenas para auxiliar a mandar o valor do pagamento para a classe
            PagamentoDinheiro pagamentoDinheiro = new PagamentoDinheiro();
            pagamentoDinheiro.setValor(valor);
            pagamento = pagamentoDinheiro; //Atribuindo o variavel pagamentoDinheiro para a interface
            pagamento.calcularTotal();//Calculando o total a pagar
            
            lblRecibo.setText(pagamento.imprmirRecibo());  //Imprimindo o recibo       
        }
        
        //Usando a mesma logica da Dinheiro para Cartão e Pix
        if("Cartão".equals(metodo)){
            PagamentoCartao pagamentoCartao = new PagamentoCartao();
            pagamentoCartao.setValor(valor);
            pagamento = pagamentoCartao; 
            pagamento.calcularTotal();
            
            lblRecibo.setText(pagamento.imprmirRecibo()); 
        }
        
        if("Pix".equals(metodo)){
            PagamentoPix pagamentoPix = new PagamentoPix();
            pagamentoPix.setValor(valor);
            pagamento = pagamentoPix; 
            pagamento.calcularTotal();
            lblRecibo.setText(pagamento.imprmirRecibo());      
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDigiteOValor;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblRecibo;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
