/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author anriu
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        spnNumero = new javax.swing.JSpinner();
        lblFrase = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNuvem = new javax.swing.JLabel();
        lblJinn = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGround.setBackground(new java.awt.Color(53, 83, 94));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnNumero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        spnNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        backGround.add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 90, 40));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(0, 0, 0));
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("<html>Vou pensar em um numero de 1 a 5, tente adivinhar</html>");
        lblFrase.setToolTipText("");
        backGround.add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 330, 70));
        lblFrase.getAccessibleContext().setAccessibleDescription("");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gênio da Lâmpada");
        backGround.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lblNuvem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/imagens/imgBallon.png"))); // NOI18N
        backGround.add(lblNuvem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -110, -1, -1));

        lblJinn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/imagens/imgJinn.png"))); // NOI18N
        backGround.add(lblJinn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        backGround.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 40));

        jPanel2.setBackground(new java.awt.Color(38, 48, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        backGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 520, 870, 100));

        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 820, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        
        //Uso do metodo getValue para pegar o valor que o usuario escolher
        int palpite = (Integer) spnNumero.getValue();
        
        //Geração de um número aleatorio de 1 a 5
        int numeroGenio = (int) (Math.random() * 5) + 1;
        
        //Teste lógico para saber se o palpite foi certo
        if(palpite == numeroGenio){
            lblFrase.setText("Acertou!!!!");
        }else{
            //Uso da tag <html> para permitir quebra de linha automatica no label
            lblFrase.setText("<html>Errou!!!! Eu pensei no numero <html>" + numeroGenio );
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JButton btnPalpite;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblJinn;
    private javax.swing.JLabel lblNuvem;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
