/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author anriu
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        spnAnoNascimento = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblAnoNascimento = new javax.swing.JLabel();
        lblSuaIdade = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResultado.setBackground(new java.awt.Color(44, 45, 61));
        lblResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Calculadora de Idade");
        lblResultado.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        spnAnoNascimento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spnAnoNascimento.setModel(new javax.swing.SpinnerNumberModel(2026, null, 2026, 1));
        spnAnoNascimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spnAnoNascimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spnAnoNascimento.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblResultado.add(spnAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 160, 40));
        spnAnoNascimento.getAccessibleContext().setAccessibleName("");

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imagens/imgIconCalculado.png"))); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        lblResultado.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 160, 40));

        lblAnoNascimento.setBackground(new java.awt.Color(255, 255, 255));
        lblAnoNascimento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAnoNascimento.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoNascimento.setText("Ano de Nascimento:");
        lblResultado.add(lblAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblSuaIdade.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSuaIdade.setForeground(new java.awt.Color(255, 255, 255));
        lblSuaIdade.setText("Sua Idade é:");
        lblResultado.add(lblSuaIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imagens/imgPessoa.png"))); // NOI18N
        lblResultado.add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        int anoNascimento = (Integer) spnAnoNascimento.getValue();
        int idade = 2026 - anoNascimento;
        lblSuaIdade.setText("Sua Idade é: " + Integer.toString(idade) + " Anos");
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblAnoNascimento;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JPanel lblResultado;
    private javax.swing.JLabel lblSuaIdade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spnAnoNascimento;
    // End of variables declaration//GEN-END:variables
}
